### ISSUE TITLE
Ensure that the execute flag 'x' for the `eventlist` utility is set in the archives for  Linux systems

### ISSUE THREAD

**Issue by jkrech** [ARM-software/CMSIS-View#48] opened 2023-05-09 11:28 UTC
When extracting the eventlist releases on Linux systems, it was observed that the execute permission flag for the eventlist executable was not set. 
The build and release actions shall ensure that the file permissions are correctly set such that the utility can be executed without any additional file permission changes by the user.

Take for example the latest release 1.1.0:
https://github.com/ARM-software/CMSIS-View/releases/download/tools%2Feventlist%2F1.1.0/eventlist-linux-amd64.tar.gz

The x flag is not set:

$ ll ./eventlist
-rw-r--r-- 1 user user 3293878 Apr 17 17:09 ./eventlist

**Comment by spcaipers-arm** [comment] 2023-05-10 08:56
Interestedly the eventlist Unix permission are correct after enforce it:

`build/linux-amd64:
total 3228
drwxr-xr-x 2 runner docker    4096 May 10 08:27 .
drwxr-xr-x 8 runner docker    4096 May 10 08:29 ..
-rwxr-xr-x 1 runner docker 3295049 May 10 08:27 eventlist

build/linux-arm[64](https://github.com/ARM-software/CMSIS-View/actions/runs/4934805464/jobs/8820299323#step:8:65):
total 3168
drwxr-xr-x 2 runner docker    4096 May 10 08:28 .
drwxr-xr-x 8 runner docker    4096 May 10 08:29 ..
-rwxr-xr-x 1 runner docker 32309 May 10 08:28 eventlist`

But once the file is archived, it loses its Unix permission:
`zipinfo eventlist-linux-amd64.zip           
Archive:  eventlist-linux-amd64.zip
Zip file size: 1882591 bytes, number of entries: 1
?rw-r--r--  2.0 unx  3295049 bl defN 23-May-10 08:29 eventlist
1 file, 3295049 bytes uncompressed, 1882459 bytes compressed:  42.9%`

**Comment by spcaipers-arm** [comment] 2023-05-10 09:07
OK, now I understood the root cause of this issue.
In the CI pipeline, it is stored temporarily the event list package as a zip file (automatically done by actions/upload-artifact@v3), this operation destroys the file permission of the files and directories. Then, we download it later on in the release job and re-package it for tar.gz (without reworking the permissions). 

I will push a proper fix.

**Comment by JonatanAntoni** [comment] 2023-07-04 14:22
This should be fixed since #50 got merged.

**Closed** 2023-12-14 10:13 UTC
